### ISSUE TITLE
When will v2.0 be released?

### ISSUE THREAD

**Issue by a-maze-d** [elixir-circuits/circuits_spi#125]
v2.0 has some nice features. It's in `v2.0.0-pre.0` for an extended period of time. There don't seem to be any open issues so maybe it's time to release it?
I have done the migration of my library without any issue and the new cirtucits_sim allows to go much further in testing.

Thus, what are we waiting for? An update would be very helpful to plan the future.

Cheers
Maze

**Comment by fhunleth** [comment]
Not waiting for anything on circuits_spi!!!! It's good to go and you'll see it on hex.pm now. Thank you for the poke!!!

**Comment by a-maze-d** [comment]
Nice. Thanks!
