### ISSUE TITLE
Segfault on second read of the same register

### ISSUE THREAD

**Issue by mroach** [elixir-circuits/circuits_spi#23]
I'm working on a driver for the RC522 RFID reader. I'm tinkering by hand, and I found that if I try to read the same register twice, I get a segfault. Granted I'm fumbling in the dark here, but I feel like a segfault shouldn't happen.

This is on a Raspberry Pi 3B with an RC522 RFID reader hooked up with SPI. The reader works fine with Python, so the wiring is all good. Here's all I do to make it happen reliably:

```elixir
iex(1)> {ok, spi} = SPI.open("spidev0.0")
{:ok, #Reference<0.3553914222.895614994.232116>}
iex(2)> SPI.transfer(ref, <<0x82, 0x00>>) 
{:ok, "  "}
iex(3)> SPI.transfer(ref, <<0x82, 0x00>>)
Segmentation fault
```

And sometimes if I try the same code again, it crashes the process and iex restarts:

```elixir
iex(3)> SPI.transfer(spi, <<0x82, 0x00>>)
** (EXIT from #PID<0.161.0>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in Inspect.Any.inspect/2
        (elixir) lib/inspect.ex:375: Inspect.Any.inspect(95, %Inspect.Opts{base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: true, printable_limit: 4096, safe: true, structs: true, syntax_colors: [atom: :cyan, string: :green, list: :default_color, boolean: :magenta, nil: :magenta, tuple: :default_color, binary: :default_color, map: :default_color], width: 80})
        (elixir) lib/kernel.ex:1929: Kernel.inspect/2
        (elixir) lib/exception.ex:1062: anonymous fn/2 in FunctionClauseError.blame/3
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/exception.ex:1061: FunctionClauseError.blame/3
        (iex) lib/iex/evaluator.ex:294: IEx.Evaluator.print_error/3
        (iex) lib/iex/evaluator.ex:210: IEx.Evaluator.eval/3
        (iex) lib/iex/evaluator.ex:94: IEx.Evaluator.loop/1

Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
```

And sometimes I get this instead, without a crash:

```elixir
iex(2)> SPI.transfer(spi, <<0x82, 0x00>>)
** (FunctionClauseError) no function clause matching in Inspect.Any.inspect/2    
    
    The following arguments were given to Inspect.Any.inspect/2:
    
        # 1
        95
    
        # 2
        %Inspect.Opts{
          base: :decimal,
          binaries: :infer,
          char_lists: :infer,
          charlists: :infer,
          limit: 48,
          pretty: true,
          printable_limit: 4096,
          safe: true,
          structs: true,
          syntax_colors: [
            reset: [:reset, :yellow],
            atom: :cyan,
            string: :green,
            list: :default_color,
            boolean: :magenta,
            nil: :magenta,
            tuple: :default_color,
            binary: :default_color,
            map: :default_color
          ],
          width: 80
        }
    
    Attempted function clauses (showing 1 out of 1):
    
        def inspect(%module{} = struct, opts)
    
    (elixir) lib/inspect.ex:375: Inspect.Any.inspect/2
    (elixir) lib/inspect/algebra.ex:380: Inspect.Algebra.container_each/6
    (elixir) lib/inspect/algebra.ex:358: Inspect.Algebra.container_doc/6
    (elixir) lib/kernel.ex:1929: Kernel.inspect/2
```

There's a good chance I'm doing something wrong, but what could be causing unpredictable output and even a segfault?

As always I'm happy to try things out to get to the bottom of it!

---

Here's some slightly more coherent code for the driver I'm trying to build. Still having a bunch of segfaults when trying to read from registers. Just using the `read/2` function directly can cause one of the errors above. https://github.com/mroach/rpi_tinker/blob/master/lib/rc522.ex

I've mostly been trying to replicate the python driver which works reliably on my Pi: https://github.com/pimylifeup/MFRC522-python/blob/master/mfrc522/MFRC522.py

**Comment by fhunleth** [comment]
That's really not good!

I'm trying to reproduce and can't. Is this with Nerves or Raspbian?

**Comment by mroach** [comment]
Ah sorry this is Raspbian with kernel 4.14.98 and Elixir 1.7.4. If you want to try it out yourself, I added your SSH keys from GitHub to the Pi. Or if you want me to try something out I'm happy to. Would running `iex` with `gdb` work? I haven't debugged nifs (or much of any C) before. But here's how to reproduce it

```shell
ssh -P 4923 pi@home.mroach.com

# there's an RFID card on the reader :)
$ ./src/pytinker/read.py
865799460258

$ cd src/tinker; iex -S mix

iex(1)> {:ok, ref} = SPI.open("spidev0.0")
{:ok, #Reference<0.325695535.3971088402.94304>}
iex(2)> RC522.initialize(ref)
** (ArgumentError) argument error
    (tinker) lib/rc522.ex:106: RC522.write/3
    (tinker) lib/rc522.ex:94: RC522.set_bit_bask/3
    (tinker) lib/rc522.ex:82: RC522.antenna_on/1
iex(2)> RC522.initialize(ref)
Segmentation fault
```

Someetimes it's as concise as:

```
iex(1)> {:ok, ref} = SPI.open("spidev0.0")
{:ok, #Reference<0.1995750157.2092302354.145240>}
iex(2)> RC522.read(ref, 0x14)
Segmentation fault
```

The segfaults happen around reading. if you do `RC522.read(ref, 0x14)` several times, you end up with a bunch of different responses followed eventually by a segfault.

Like I say, I'm sure I'm doing something wrong translating things from Python and other C/C++ code so I don't expect it to actually work yet, but it'd be nice to figure out the segfaults and `inspect/2` errors.

**Comment by fhunleth** [comment]
@mroach Thanks for sharing your Pi. I have your Pi running from the branch in the linked PR. After the reviews, I'll make a release.

This issue also affects `circuits_i2c` so huge thanks on finding it. I'm amazed that things have been working as well as they have with this issue.

**Comment by mroach** [comment]
Thanks so much for digging into it and fixing it! Working great so far now. I'm looking forward to getting the driver done now :) 🚀 ❤️
